# Generated by Django 4.2.4 on 2023-08-13 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='тема')),
                ('body', models.TextField(blank=True, null=True, verbose_name='содержание')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.RemoveField(
            model_name='mailingsettings',
            name='mailing',
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='customer',
            field=models.ManyToManyField(to='mailing.customer', verbose_name='клиент'),
        ),
        migrations.DeleteModel(
            name='Mailing',
        ),
        migrations.AddField(
            model_name='message',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailingsettings'),
        ),
    ]
