# Generated by Django 4.2.4 on 2023-08-13 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_rename_message_mailing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='settings',
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='рассылка'),
        ),
    ]
