# Generated by Django 4.2.4 on 2023-08-17 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_remove_customer_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='mailing_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingsettings'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='frequency',
            field=models.PositiveIntegerField(choices=[('D', 'DAY'), ('W', 'WEEK'), ('M', 'MONTH')], verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='status',
            field=models.CharField(choices=[('CR', 'CREATED'), ('LA', 'LAUNCHED'), ('CO', 'COMPLETED')], max_length=15, verbose_name='статус рассылки'),
        ),
    ]
