# Generated by Django 4.2.4 on 2023-08-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_log_mailing_settings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='frequency',
            field=models.CharField(choices=[('D', 'DAY'), ('W', 'WEEK'), ('M', 'MONTH')], max_length=10, verbose_name='периодичность'),
        ),
    ]
