# Generated by Django 4.2.4 on 2023-08-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_log_status_alter_mailingsettings_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='is_block',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='заблокирована'),
        ),
    ]
