# Generated by Django 4.2.4 on 2023-08-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0013_alter_mailingsettings_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='customer',
            field=models.ManyToManyField(to='mailing.customer', verbose_name='клиент'),
        ),
    ]
