# Generated by Django 4.2.4 on 2023-08-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0017_alter_mailingsettings_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingsettings',
            name='owner',
        ),
    ]
