# Generated by Django 4.2.4 on 2023-08-20 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0019_mailingsettings_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingsettings',
            name='owner',
        ),
        migrations.AddField(
            model_name='mailing',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец рассылки'),
        ),
    ]
