# Generated by Django 4.2.4 on 2023-08-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0023_customer_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('set_block', 'Can block mailing')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
