# Generated by Django 4.2.4 on 2023-08-20 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0025_remove_mailingsettings_mailing_mailing_mailing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='тема')),
                ('body', models.TextField(blank=True, null=True, verbose_name='содержание')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('set_block', 'Can block mailing')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='body',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='mailing',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='title',
        ),
        migrations.AddField(
            model_name='mailing',
            name='customer',
            field=models.ManyToManyField(to='mailing.customer', verbose_name='клиент'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='distribution_settings',
            field=models.TimeField(default='12:00', verbose_name='время рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='frequency',
            field=models.CharField(blank=True, choices=[('O', 'ONCE'), ('D', 'DAY'), ('W', 'WEEK'), ('M', 'MONTH')], max_length=10, null=True, verbose_name='периодичность'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_block',
            field=models.BooleanField(default=False, verbose_name='заблокирована'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='status',
            field=models.CharField(blank=True, choices=[('CR', 'CREATED'), ('LA', 'LAUNCHED'), ('CO', 'COMPLETED')], default='CR', max_length=15, null=True, verbose_name='статус рассылки'),
        ),
        migrations.AlterField(
            model_name='log',
            name='mailing_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing'),
        ),
        migrations.DeleteModel(
            name='MailingSettings',
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='рассылка'),
        ),
    ]
