# Generated by Django 4.2.4 on 2023-08-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0027_remove_mailing_message_message_mailing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='owner',
        ),
    ]
