# Generated by Django 4.2.4 on 2023-08-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0028_remove_customer_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='distribution_settings',
            field=models.TimeField(default='10:00', verbose_name='время рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='frequency',
            field=models.CharField(choices=[('O', 'ONCE'), ('D', 'DAY'), ('W', 'WEEK'), ('M', 'MONTH')], default='O', max_length=10, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('CR', 'CREATED'), ('LA', 'LAUNCHED'), ('CO', 'COMPLETED')], default='CR', max_length=15, verbose_name='статус рассылки'),
        ),
    ]
