# Generated by Django 4.2.4 on 2023-08-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0031_remove_mailing_message_message_mailing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['distribution_settings'], 'permissions': [('set_block', 'Can block mailing')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AddField(
            model_name='mailing',
            name='last_mailing_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='последняя рассылка'),
        ),
    ]
